name: Notebook Lint
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ v2b-dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install nbformat

      - name: Validate notebooks (schema) + ensure minimal outputs
        run: |
          set -e
          FILES="$(git ls-files '*.ipynb' || true)"
          if [ -z "$FILES" ]; then
            echo "No notebooks found in repo. Skipping lint."
            exit 0
          fi
          python - << 'PY'
          import sys, pathlib, nbformat
          invalid = []
          with_outputs = []
          for p in pathlib.Path(".").rglob("*.ipynb"):
              try:
                  nb = nbformat.read(p, as_version=4)
                  nbformat.validate(nb)
              except Exception as e:
                  print(f"[INVALID] {p}: {e}")
                  invalid.append(str(p))
                  continue
              # check for any cell outputs
              if any(c.get("outputs") for c in nb.get("cells", []) if isinstance(c, dict)):
                  with_outputs.append(str(p))
          if invalid:
              print("\nInvalid notebooks:")
              print("\n".join(invalid))
              sys.exit(1)
          if with_outputs:
              print("\nNotebooks with outputs (strip before commit):")
              print("\n".join(sorted(set(with_outputs))))
              sys.exit(1)
          print("All notebooks valid and output-free.")
          PY
